### ISSUE TITLE
How to get tps ??? no grafana json

### ISSUE THREAD

**Issue by krast** [monkey-codes/spring-boot-restful#2]

**Comment by monkey-codes** [comment]
I believe you can use the [rate](https://prometheus.io/docs/querying/functions/#rate) provided by prometheus in grafana to calculate TPS. In this example, the avg TPS is calculated in buckets of 1 min.
```
rate(counter_status_201_repository[1m])
``` 
![sample](https://res.cloudinary.com/monkey-codes/image/upload/v1484206790/grafana-tps-example.png)

**Comment by krast** [comment]
@monkey-codes Thanks for replying to the issues.
I am trying to add some monitor for zuul. I can't find a springcloud official examples. 
I find your blog, it's a great example for me.
Now, I know how to do it.
